const FETCH_IMAGES_SUCCESS = 'FETCH_IMAGES_SUCCESS';
const FETCH_IMAGES_FAILED = 'FETCH_IMAGES_FAILED';
const FETCH_IMAGES = 'FETCH_IMAGES';
const TOOGLE_COMMENTS = 'TOOGLE_COMMENTS';
const CLOSE_COMMENTS = 'CLOSE_COMMENTS';
const OPEN_COMMENTS = 'OPEN_COMMENTS';
const ADD_COMMENT = 'ADD_COMMENT';
const SAVE_COMMENT = 'SAVE_COMMENT';
const ADD_COMMENT_TO_LIST = 'ADD_COMMENT_TO_LIST';
const CREATE_USER = 'CREATE_USER';
const ADD_USER = 'ADD_USER';
const DELETE_COMMENT = 'DELETE_COMMENT';
const REMOVE_COMMENT = 'REMOVE_COMMENT';
const UPDATE_COMMENTS_LIST = 'UPDATE_COMMENTS_LIST';
const UPDATE_COMMENT = 'UPDATE_COMMENT';
const MODIFY_COMMENT = 'MODIFY_COMMENT';
export {
  FETCH_IMAGES_SUCCESS,
  FETCH_IMAGES_FAILED,
  FETCH_IMAGES,
  CLOSE_COMMENTS,
  TOOGLE_COMMENTS,
  OPEN_COMMENTS,
  ADD_COMMENT,
  SAVE_COMMENT,
  ADD_COMMENT_TO_LIST,
  ADD_USER,
  CREATE_USER,
  REMOVE_COMMENT,
  DELETE_COMMENT,
  UPDATE_COMMENTS_LIST,
  UPDATE_COMMENT,
  MODIFY_COMMENT,
};
